### ISSUE TITLE
XML parse error

### ISSUE THREAD

**Issue by dskrad** [dogsheep/evernote-to-sqlite#11]
I am on Windows 10 using Windows Subsystem for Linux, Python 3.8. I installed evernote-to-sqlite via pipx (in a venv). I tried using enex files from the latest version of Evernote for Windows (10.6.9 which only lets you export 50 notes at a time) and from Legacy Evernote (6.25.2.9198 which lets you export all your notes at once). The enex file from latest evernote gives this error:

    File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML parser.feed(text)
    xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 6

The enex file from Legacy Evernote gives this error:

    File "/home/david/.local/pipx/venvs/evernote-to-sqlite/lib/python3.8/site-packages/evernote_to_sqlite/utils.py", line 28, in save_note
    updated = note.find("updated").text
    AttributeError: 'NoneType' object has no attribute 'text'

**Comment by dskrad** [comment]
I solved this issue by modifying line 31 of utils.py

    content = ET.tostring(ET.fromstring(content_xml.strip())).decode("utf-8")

**Comment by simonw** [comment]
Thanks for the fix!
